//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDeOrden
    {
        public int Id { get; set; }
        public int CantidadOrden { get; set; }
        public string NotaDetalleOrden { get; set; }
        public bool EstadoDetalleOrden { get; set; }
        public int MenuId { get; set; }
        public int OrdenId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
