//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Receta = new HashSet<Receta>();
            this.DetallesDeOrden = new HashSet<DetalleDeOrden>();
        }
    
        public int Id { get; set; }
        public string CodigoMenu { get; set; }
        public string DescripcionPlatillo { get; set; }
        public double PrecioPlatillo { get; set; }
        public bool EstadoPlatillo { get; set; }
        public int TipoDePlatilloId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Receta { get; set; }
        public virtual CategoriaMenu TipoDePlatillo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDeOrden> DetallesDeOrden { get; set; }
    }
}
