//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public int Id { get; set; }
        public string DescripcionReceta { get; set; }
        public string TiempoEstimadoReceta { get; set; }
        public bool EstadoReceta { get; set; }
        public string IngredientesPrincipales { get; set; }
        public int MenuId { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
